import { User } from './user.model'

export const findLastId = async (): Promise<string | undefined> => {
  const lastUser = await User.findOne({}, { userId: 1, _id: 0 })
    .sort({
      createdAt: -1
    })
    .lean()
  console.log(lastUser)
  return lastUser?.userId
}

export const autogeneratedId = async (): Promise<string> => {
  try {
    const lastId = (await findLastId()) || '0'

    // const currentId = lastId || '0'.repeat(5)

    // console.log(currentId)
    const incrementedId = (parseInt(lastId) + 1).toString().padStart(5, '0')
    console.log(incrementedId)

    // Update the last used ID in the database
    await User.create({ userId: incrementedId })

    return incrementedId
  } catch (error) {
    console.error('Error generating ID:', error)
    throw new Error('Failed to generate ID')
  }
}
