import { IUser } from './user.interface'
import { User } from './user.model'
import { autogeneratedId } from './user.utls'

const createUser = async (user: IUser): Promise<IUser | null> => {
  // console.log('i am from userService', user)
  const userid = await autogeneratedId()
  user.userId = userid
  // eslint-disable-next-line no-unused-expressions

  const result = await User.create(user)
  // console.log(result)

  return result
}

export const userService = {
  createUser
}
